module.exports = {
  PORT_NUMBER: 6969,
  TICK_TIME: 1000 / 10, // (1s in ms) / fps
  GAME_READY_TIME: 5000,
  MIN_TARGET: -99,
  MAX_TARGET: 100,
  MIN_DROP: -9,
  MAX_DROP: 10
};

module.exports.messageType = {
  PING: "PING",

  //server messages
  LOGIN_CONFIRMATION: "LOGIN_CONFIRMATION",
  GAME_INIT: "GAME_INIT",
  GAME_START: "GAME_START",
  GAME_FINISH: "GAME_FINISH",
  GAME_STATE_UPDATE: "GAME_STATE_UPDATE",
  GAME_DROPPED_ITEM: "GAME_DROPPED_ITEM",
  GAME_FOUND: "GAME_FOUND",
  GET_RANKINGS: "GET_RANKINGS",

  //client messages
  LOGIN: "LOGIN",
  FIND_GAME: "FIND_GAME",
  PLAYER_ACTION: "PLAYER_ACTION",
  CREATE_USER: "CREATE_USER"
};

module.exports.playerActionType = {
  ADDITION: "ADDITION",
  SUBTRACTION: "SUBTRACTION",
  MULTIPLICATION: "MULTIPLICATION",
  DIVISION: "DIVISION",
  GET_NUMBER: "GET_NUMBER",
  USE_ITEM: "USE_ITEM",
  GET_ITEM: "GET_ITEM"
};

module.exports.gampeType = {
  SINGLEPLAYER: "SINGLEPLAYER",
  RANKED: "RANKED",
  GROUP_GAME: "GROUP_GAME",
  SECRET_MODE: "SECRET_MODE"
};
